### ISSUE TITLE
Crashes when using a redump PS2 dat

### ISSUE THREAD

**Issue by Nioh8** [drakewill-CRL/ROMSorter#1]
been trying to rename a few ps2 isos i have, so grabbed the dat file on redumps website, as soon as i add the DAT file the program crashes and then when trying to open it again it crashes again, had to delete local data to get it reset, any ideas thanks.

**Comment by drakewill-CRL** [comment]
This should be resolved as of Release 4. It should now simply skip reading a DAT file if it would fail to do so on load.
